#!/usr/bin/env bash

alias chrome='open -na "Google Chrome"' # '-n' is for opening new instance
alias c='chrome'
alias chrome-beta='open -na "Google Chrome Beta"' # '-n' is for opening new instance
alias cb='chrome-beta'

alias whereis='which'

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Copy pwd to clipboard
alias cpwd="pwd|tr -d '\n'|pbcopy"

# Cask
alias cask="brew cask"

# Sublime
alias subl="sublime"
