#!/usr/bin/env bash


# Random wallpaper from Unsplash
ruw (){
    wallpaper_dir=$HOME/Pictures/Wallpapers
    img_name=$(date +%F_%H-%M-%S)
    
    $(get_and_save_wallpaper)

    osascript -e "tell application \"System Events\" to set picture of every desktop to \"${wallpaper_dir}/${img_name}.png\""
    killall Dock
}




