#!/usr/bin/env bash

set_wallpaper () {
    osascript -e "tell application \"System Events\" to set picture of every desktop to \"${WALLPAPER_DIR}/${img_name}\""
    killall Dock
}

set_resolution (){
    display_resolution="2880x1800"
}


chrome-search() {
  open -na "Google Chrome" --args --profile-directory="Profile 3" "? $*"
}

chrome-work-search() {
  open -na "Google Chrome" --args --profile-directory="Profile 1" "? $*"
}